import Link from "next/link";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/dashboard/print-button";
import { requireProfile } from "@/lib/auth";
import { calculateBookletResults, formatExamDuration, formatExamSchedule, type ExamBooklet } from "@/lib/exams";
import { toPersianDigits } from "@/lib/persian-date";
import "./report.css";

type Attempt = { attempt_id:string; student_name:string; score:number|null; correct_answers:number|null; incorrect_answers:number|null; unanswered_count:number|null; total_questions:number|null; answers:Record<string,number>|null; submitted_at:string };
const percent=(value:number)=>`${toPersianDigits(value.toLocaleString("fa-IR",{maximumFractionDigits:2}))}٪`;
const submittedAtFormatter=new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tehran"});

export default async function PrintableExamReport({params}:{params:Promise<{id:string;attemptId:string}>}){
 const {id,attemptId}=await params; const {supabase,profile}=await requireProfile(["counselor"]);
 const [{data:exam},{data:attemptsData}]=await Promise.all([supabase.from("exams").select("id,title,description,starts_at,duration_minutes,exam_booklets(id,title,pdf_url,question_count,start_question_number,end_question_number,duration_minutes,sort_order,key_answers)").eq("id",id).eq("counselor_id",profile.id).single(),supabase.rpc("exam_attempts_for_counselor",{target_exam_id:id})]);
 const attempt=((attemptsData??[]) as Attempt[]).find(item=>item.attempt_id===attemptId); if(!exam||!attempt)notFound();
 const booklets=((exam.exam_booklets??[]) as ExamBooklet[]).sort((a,b)=>a.sort_order-b.sort_order); const rows=calculateBookletResults(booklets,attempt.answers); const total=attempt.total_questions??rows.reduce((sum,row)=>sum+row.total,0);
 const chartWidth=760,chartHeight=190,chartLeft=52,chartRight=18,chartTop=12,chartBottom=42,plotWidth=chartWidth-chartLeft-chartRight,plotHeight=chartHeight-chartTop-chartBottom; const ticks=[-30,-10,10,30,50,70,90,100];
 const chartX=(index:number)=>chartLeft+(rows.length===1?plotWidth/2:index*plotWidth/Math.max(1,rows.length-1)); const chartY=(value:number)=>chartTop+((100-Math.max(-30,Math.min(100,value)))/130)*plotHeight; const points=rows.map((row,index)=>`${chartX(index)},${chartY(row.percentage)}`).join(" ");
 return <main className="exam-report-page" dir="rtl"><div className="exam-report-toolbar"><Link className="button secondary" href={`/dashboard/counselor/exams/${id}`}>بازگشت به نتایج</Link><PrintButton/></div><article className="exam-report-sheet">
  <header className="exam-report-header"><div className="exam-report-brand"><span>نووا</span><small>مسیر روشن موفقیت تحصیلی</small></div><div className="exam-report-heading"><span>کارنامه آزمون</span><h1>{exam.title}</h1></div><div className="exam-report-student"><span>دانش‌آموز</span><strong>{attempt.student_name||"دانش‌آموز نووا"}</strong></div></header>
  <section className="exam-report-meta"><div><span>تاریخ و زمان شروع</span><strong>{formatExamSchedule(exam.starts_at)}</strong></div><div><span>زمان ثبت پاسخ‌ها</span><strong>{submittedAtFormatter.format(new Date(attempt.submitted_at))}</strong></div><div><span>مدت کل آزمون</span><strong>{formatExamDuration(exam.duration_minutes)}</strong></div><div><span>تعداد کل سؤالات</span><strong>{toPersianDigits(total)}</strong></div></section>
  <section className="exam-report-summary"><div className="correct"><span>پاسخ درست</span><strong>{toPersianDigits(attempt.correct_answers??0)}</strong></div><div className="wrong"><span>پاسخ غلط</span><strong>{toPersianDigits(attempt.incorrect_answers??0)}</strong></div><div className="blank"><span>نزده</span><strong>{toPersianDigits(attempt.unanswered_count??0)}</strong></div><div className="score"><span>درصد کل</span><strong>{percent(attempt.score??0)}</strong></div></section>
  <section className="exam-report-content"><div className="exam-report-analysis"><h2>تحلیل دروس</h2><table className="exam-report-table"><thead><tr><th>درس</th><th>سؤال</th><th>درست</th><th>غلط</th><th>نزده</th><th>درصد</th></tr></thead><tbody>{rows.map(row=><tr key={row.title}><th>{row.title}</th><td>{toPersianDigits(row.total)}</td><td>{toPersianDigits(row.correct)}</td><td>{toPersianDigits(row.incorrect)}</td><td>{toPersianDigits(row.unanswered)}</td><td>{percent(row.percentage)}</td></tr>)}<tr className="total-row"><th>جمع کل</th><td>{toPersianDigits(total)}</td><td>{toPersianDigits(attempt.correct_answers??0)}</td><td>{toPersianDigits(attempt.incorrect_answers??0)}</td><td>{toPersianDigits(attempt.unanswered_count??0)}</td><td>{percent(attempt.score??0)}</td></tr></tbody></table></div>
   <div className="exam-report-chart-card"><h2>نمودار عملکرد درسی</h2><svg className="exam-report-chart" viewBox={`0 0 ${chartWidth} ${chartHeight}`} role="img" aria-label="نمودار درصد عملکرد در درس‌های آزمون">{ticks.map(tick=><g key={tick}><line x1={chartLeft} x2={chartWidth-chartRight} y1={chartY(tick)} y2={chartY(tick)} className={tick===0?"axis-zero":"grid-line"}/><text x={chartLeft-8} y={chartY(tick)+4} className="axis-label">{toPersianDigits(tick)}</text></g>)}{rows.length>1&&<polyline points={points} className="performance-line"/>}{rows.map((row,index)=><g key={row.title}><line x1={chartX(index)} x2={chartX(index)} y1={chartY(0)} y2={chartY(row.percentage)} className="performance-stem"/><circle cx={chartX(index)} cy={chartY(row.percentage)} r="5" className="performance-dot"/><text x={chartX(index)} y={Math.max(11,chartY(row.percentage)-10)} className="value-label">{percent(row.percentage)}</text><text x={chartX(index)} y={chartHeight-12} className="subject-label">{row.title}</text></g>)}</svg></div>
  </section><footer className="exam-report-footer"><span>نووا · مسیر روشن موفقیت تحصیلی</span><span>مشاور: {profile.full_name||"مشاور نووا"}</span></footer>
 </article></main>;
}
